package com.example.hoteltvapptemplate.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFD0BCFF)
val md_theme_dark_onPrimary = Color(0xFF3B0B89)
val md_theme_dark_primaryContainer = Color(0xFF522DA0)
val md_theme_dark_onPrimaryContainer = Color(0xFFE9DDFF)
val md_theme_dark_secondary = Color(0xFFCABEFF)
val md_theme_dark_onSecondary = Color(0xFF312075)
val md_theme_dark_secondaryContainer = Color(0xFF48398D)
val md_theme_dark_onSecondaryContainer = Color(0xFFE6DEFF)
val md_theme_dark_tertiary = Color(0xFFDFB7FF)
val md_theme_dark_onTertiary = Color(0xFF451969)
val md_theme_dark_tertiaryContainer = Color(0xFF5D3282)
val md_theme_dark_onTertiaryContainer = Color(0xFFF1DAFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF24005A)
val md_theme_dark_onBackground = Color(0xFFEADDFF)
val md_theme_dark_surface = Color(0xFF24005A)
val md_theme_dark_onSurface = Color(0xFFEADDFF)
val md_theme_dark_surfaceVariant = Color(0xFF49454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4CF)
val md_theme_dark_outline = Color(0xFF948F99)
val md_theme_dark_inverseOnSurface = Color(0xFF24005A)
val md_theme_dark_inverseSurface = Color(0xFFEADDFF)
val md_theme_dark_inversePrimary = Color(0xFF6A48BA)
val md_theme_dark_surfaceTint = Color(0xFFD0BCFF)
val md_theme_dark_outlineVariant = Color(0xFF49454E)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_transparent = Color(0x00000000)